<?php
echo $this->headtitle($this->escapehtml($this->translate('Thêm')));
$form = $this->form;
?>
<style>
    .form-group .parsley-errors-list {
        order: 5;
    }
</style>
<form class="invoice-form" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Tạo hoá đơn</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên hoá đơn</label>
                                <?= $this->formelement($form->get('description')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên hoá đơn', 'required' => 'required', 'data-parsley-error-message' => 'Hoá đơn không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('description'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="form-group">
                        <a class="add-product-item-invoice btn btn-primary waves-effect waves-light">Thêm vật liệu</a>
                    </div>

                    <div class="list-product-material-invoice">
                        <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Vật liệu</label>
                                <?= $this->formelement($form->get('materialId')->setAttributes(['name' => 'materialId[]','class' => 'form-control select-ajax-material', 'required' => 'required','data-cong' => 'true', 'placeholder'=>'Vật liệu','data-parsley-type' => 'string', 'data-parsley-error-message' => 'Vật liệu không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('materialId'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Đơn giá</label>
                                <?= $this->formelement($form->get('price')->setAttributes(['name' => 'price[]','class' => 'form-control autonumber', 'placeholder'=>'Đơn giá', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Số lượng</label>
                                <?= $this->formelement($form->get('quantity')->setAttributes(['class' => 'form-control', 'placeholder'=>'Số lượng', 'required' => 'required', 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('quantity'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Thành tiền</label>
                                <?= $this->formelement($form->get('intoMoney')->setAttributes(['name' => 'quantity[]','class' => 'form-control autonumber', 'placeholder'=>'Thành tiền'])) ?>
                                <?= $this->formelementerrors($form->get('intoMoney'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'loadHomepage btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <!-- End col-sm-8 -->
    </div>
</form>
