<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách hoá đơn')));
$domainUrl = $this->home()->getDomain();
$domainUrl ? $_SERVER['HTTP_HOST'] = $domainUrl:$_SERVER['HTTP_HOST'];
$option = $this->option;
?>
<input type="hidden" class="updateHomepage" />
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/invoice/add" class="btn btn-default waves-effect waves-light">Tạo hoá đơn</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                    $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control','placeholder'=>'Tên hoá đơn', 'value' => isset($this->query['name']) ? $this->query['name']:'']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('status')->setAttributes(['class' => 'form-control']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('type')->setAttributes(['class' => 'form-control']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <?php
                    echo $dg = new \Admin\Dg\DgInvoice ( array (
                        'data' => $this->results->getData (),
                        'paging' => $this->results->getPaging (),
                        'rowCount' => $this->results->getRowCount (),
                        'rowInPage' => $this->results->getRowInPage (),
                        'setup' => true,
                        'url' => $this->url,
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

