<?php
echo $this->headtitle($this->escapehtml($this->translate('Xuất vật liệu')));
$form = $this->form;
$query = $this->query;
?>
<form class="material-form" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Xuất vật liệu</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên hoá đơn</label>
                                <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control', 'value' => $query->name, 'placeholder'=>'Tên hoá đơn', 'required' => 'required', 'data-parsley-error-message' => 'Tên sản phẩm không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="form-group">
                        <a class="add-product-item btn btn-primary waves-effect waves-light">Thêm vật liệu</a>
                    </div>
                    <div class="list-product-material">
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Vật liệu</label>
                                    <?= $this->formelement($form->get('materialId')->setAttributes(['name' => 'materialId[]','class' => 'form-control select-ajax-material','data-cong' => 'false', 'required' => 'required', 'placeholder'=>'Vật liệu','data-parsley-type' => 'string', 'data-parsley-error-message' => 'Vật liệu không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('materialId'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Đơn giá</label>
                                    <?= $this->formelement($form->get('price')->setAttributes(['name' => 'price[]','class' => 'price_field form-control autonumber', 'placeholder'=>'Đơn giá', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Số lượng</label>
                                    <?= $this->formelement($form->get('quantity')->setAttributes(['name' => 'quantity[]','class' => 'quantity_field form-control', 'placeholder'=>'Số lượng', 'required' => 'required', 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('quantity'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Thành tiền</label>
                                    <?= $this->formelement($form->get('intoMoney')->setAttributes(['name' => 'intoMoney[]','class' => 'intoMoney_field form-control autonumber', 'placeholder'=>'Thành tiền'])) ?>
                                    <?= $this->formelementerrors($form->get('intoMoney'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'loadHomepage btn btn-default', 'value'=> 'Tạo hoá đơn']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <!-- End col-sm-8 -->
    </div>
</form>
