<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách hóa đơn')));
echo $this->headscript()->prependFile($this->basepath().'/js/order/order.js');
//print_r($this->results);die;
$order = $this->results['orders'];
?>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="" class="btn btn-default waves-effect waves-light">Đơn hàng</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                    $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('id')->setAttributes(['class' => 'form-control','placeholder'=>'Id']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('title')->setAttributes(['class' => 'form-control','placeholder'=>'Tên khách hàng']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="dg-container">
                        <table class="dg table table-bordered table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th style="text-align: center;width: 8%;">Order Id</th>
                                    <th style="vertical-align: middle;width: 12%;">Tên</th>
                                    <th>Địa chỉ</th>
                                    <th style="width: 40%">Sản phẩm</th>
                                    <th style="text-align: center;width: 8%">Trạng thái</th>
                                    <th style="text-align: center;width: 5%">Xóa</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(!empty($order)): ?>
                                    <?php foreach($order as $k => $v): ?>
                                    <tr class="even">
                                        <td class="id" style="text-align: center;vertical-align: middle"><?php echo $k ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['customerName'] ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['customerAddress'] ?></td>
                                        <td style="">
                                            <?php foreach ($v['products'] as $p => $pv): ?>
                                                <p><?php echo '<strong>'.$pv['productCode'].'</strong>' . ' - ' . $pv['productName']; ?></p>
                                            <?php endforeach; ?>
                                        </td>
                                        <td style="text-align: center;vertical-align: middle"><?php echo $v['statusName'] ?></td>
                                        <td style="text-align: center;vertical-align: middle"></td>
                                    </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <div class="dataTables_paginate paging_bootstrap pagination pagination__option">
                            <ul class="pagination"><li class="prev disabled"><a><span>Prev</span></a></li><li><a>1 / 6</a></li><li><a class="btn-default" href="?page=2" title="Trang trước"><span>Next</span></a></li></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

