<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách hóa đơn')));
echo $this->headscript()->prependFile($this->basepath().'/js/order/order.js');
//print_r($this->results);die;
$order = $this->results['orders'];
$total = $this->results['totalPages'];
$page = $this->results['page'] ? $this->results['page']:1;
$query = $this->query;
$page_prev = ($page == 1 ? 1:$page-1);
$page_prev = preg_replace ( '/page=([0-9])/','page='.$page_prev, $query );
$page_next = ($total == $page ? $page:$page + 1);
$page_next = preg_replace ( '/page=([0-9])/','page='.$page_next, $query );
?>

<style>
    .list_product p:last-child {
        margin: 0;
    }
</style>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="" class="btn btn-default waves-effect waves-light">Đơn hàng</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                    $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('page')->setAttributes(['value' => $page]))?>
                                        <?=$this->formelement($form->get('id')->setAttributes(['class' => 'form-control','placeholder'=>'Id']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('title')->setAttributes(['class' => 'form-control','placeholder'=>'Tên khách hàng']))?>
                                    </div>
                                    <div class="form-group">
                                        <?=$this->formelement($form->get('status')->setAttributes(['class' => 'form-control']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="dg-container">
                        <table class="dg table table-bordered table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th style="text-align: center;width: 8%;">Order Id</th>
                                    <th style="vertical-align: middle;width: 12%;">Tên</th>
                                    <th>Địa chỉ</th>
                                    <th style="width: 40%">Sản phẩm</th>
                                    <th style="text-align: center;width: 8%">Trạng thái</th>
                                    <th style="text-align: center;width: 10%">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(!empty($order)): ?>
                                    <?php foreach($order as $k => $v): ?>
                                    <tr class="even">
                                        <td class="id" style="text-align: center;vertical-align: middle"><?php echo $k ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['customerName'] ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['customerAddress'] ?></td>
                                        <td class="list_product">
                                            <?php foreach ($v['products'] as $p => $pv): ?>
                                                <p><?php echo '<strong>'.$pv['productCode'].'</strong>' . ' - ' . $pv['productName']; ?></p>
                                            <?php endforeach; ?>
                                        </td>
                                        <td style="text-align: center;vertical-align: middle"><?php echo $v['statusName'] ?></td>
                                        <td style="text-align: center;vertical-align: middle"></td>
                                    </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <div class="dataTables_paginate paging_bootstrap pagination pagination__option">
                            <ul class="pagination">
                                <li class="prev"><a class="" href="<?php echo 'order?'. $page_prev; ?>"><span>Trang sau</span></a></li>
                                <li><a class="btn-default"><?php echo $page .'/'.$total;  ?></a></li>
                                <li><a class="" href="<?php echo 'order?'. $page_next ?>" title="Trang trước"><span>Trang trước</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

