<?php
echo $this->headtitle($this->escapehtml($this->translate('Thêm')));
$form = $this->form;
?>

<form class="material-form" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Thêm vật liệu</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Đơn vị</label>
                                <?= $this->formelement($form->get('type')->setAttributes(['class' => 'form-control material-type', 'placeholder'=>'Số điện thoại', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('type'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên vật liệu</label>
                                <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên vật liệu', 'required' => 'required', 'data-parsley-error-message' => 'Tên vật liệu không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Đơn giá</label>
                                <?= $this->formelement($form->get('price')->setAttributes(['class' => 'form-control autonumber', 'placeholder'=>'Đơn giá', 'disabled' => true, 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Số tiền không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Nhà cung cấp</label>
                                <?= $this->formelement($form->get('manufactureId')->setAttributes(['class' => 'form-control'])) ?>
                                <?= $this->formelementerrors($form->get('manufactureId'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                    </div>
                    <div class="row">

                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'loadHomepage btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <!-- End col-sm-8 -->
    </div>
</form>
