<?php
$form = $this->form;
$item = $this->item;
?>

<?php
    for($c = 1; $c <= count($item); $c++):
?>
<div class="row">
    <div class="col-sm-3">
        <div class="form-group">
            <label class="control-label" for="firstName">Vật liệu</label>
            <?= $this->formelement($form->get('materialId')->setAttributes(['name' => 'materialId[]','class' => 'form-control select-ajax-material', 'required' => 'required', 'placeholder'=>'Vật liệu','data-parsley-type' => 'string', 'data-parsley-error-message' => 'Vật liệu không được để trống'])) ?>
            <?= $this->formelementerrors($form->get('materialId'),['class' => 'parsley-errors-list filled']) ?>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="form-group">
            <label class="control-label" for="firstName">Đơn giá</label>
            <?= $this->formelement($form->get('price')->setAttributes(['name' => 'price[]','class' => 'price_field form-control autonumber', 'placeholder'=>'Đơn giá', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
            <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="form-group">
            <label class="control-label" for="firstName">Số lượng</label>
            <?= $this->formelement($form->get('quantity')->setAttributes(['name' => 'quantity[]','class' => 'quantity_field form-control', 'placeholder'=>'Số lượng', 'required' => 'required', 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Không được để trống'])) ?>
            <?= $this->formelementerrors($form->get('quantity'),['class' => 'parsley-errors-list filled']) ?>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="form-group">
            <label class="control-label" for="firstName">Thành tiền</label>
            <div class="<?= $c > 1 ? 'input-group':'' ?>">
                <?= $this->formelement($form->get('intoMoney')->setAttributes(['name' => 'intoMoney[]','class' => 'intoMoney_field form-control autonumber', 'placeholder'=>'Thành tiền'])) ?>
                <?= $this->formelementerrors($form->get('intoMoney'),['class' => 'parsley-errors-list filled']) ?>
                <?php if($c > 1): ?>
                <span class="input-group-btn">
                    <button type="button" id="check-minutes" class="btn "> - </button>
                </span>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php endfor; ?>

<script>
    jQuery(document).ready(function () {
    $('.autonumber').autoNumeric('init', {'mDec':0});

    var select_material = $(".select-ajax-material");
    select_material.each(function () {
        var selectMaterial = $(this);
        var length = selectMaterial.attr('data-length') ? selectMaterial.attr('data-length'):5;
        var placeholderProduct = selectMaterial.attr('data-placeholder') ? selectMaterial.attr('data-placeholder'):'Vật liệu';
        if(selectMaterial.length) {
            selectMaterial.select2({
                placeholder: placeholderProduct,
                multiple: false,
                ajax: {
                    url: "/admin/product/related",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            keyword: params.term, // search term
                            material: true
                        };
                    },
                    processResults: function (data, params) {
                        return {
                            results: data,
                        };
                    },
                    templateSelection: function(container) {
                        $(container.element).attr("data-source", 'hehe');
                        return container.text;
                    },
                    cache: true
                },
            });
            var parent = selectMaterial.closest("div.row");
            selectMaterial.on("select2:select", function (evt) {
                var element = evt.params.data.element;
                var $element = $(element);
                console.log($(this).val());
                parent.find('input.price_field').val(evt.params.data.price).trigger('focusout');
                $element.detach();
                $(this).append($element);
                $(this).trigger("change");
            });

            var input_price_invoice = parent.find('input.price_field');
            var quantity = parent.find('input.quantity_field');
            var intoMoney = parent.find('input.intoMoney_field');

            quantity.keyup(calculate);

            function calculate(e) {
                var value_price = input_price_invoice.val();
                value_price = value_price.replace(",", "");
                var value_quantity = quantity.val();
                value_quantity = value_quantity.replace(",", "");

                intoMoney.val(value_price * value_quantity);
                intoMoney.autoNumeric().trigger('focusout');
            }
        }
    });

});

</script>
