<?php
echo $this->headtitle($this->escapehtml($this->translate('Thêm')));
$form = $this->form;
$materials = $this->materials;
$query = $this->query;
$image = $form->get('image')->getValue();

?>
<form class="material-form" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-8">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Thêm sản phẩm vật liệu</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên sản phẩm</label>
                                <input type="hidden" name="name" value="<?= $form->get('name')->getValue() ?>" >
                                <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên sản phẩm','disabled' => true, 'required' => 'required', 'data-parsley-error-message' => 'Tên sản phẩm không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Mã sản phẩm</label>
                                <input type="hidden" name="productId" value="<?= $form->get('productId')->getValue() ?>" >
                                <?= $this->formelement($form->get('productId')->setAttributes(['class' => 'form-control', 'placeholder'=>'Mã sản phẩm','disabled' => true, 'required' => 'required', 'data-parsley-error-message' => 'Mã sản phẩm không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('productId'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="form-group">
                        <a class="edit-product-item btn btn-primary waves-effect waves-light" data-product-id="<?= $form->get('productId')->getValue() ?>">Thêm vật liệu</a>
                    </div>
                    <div class="list-product-material">
                        <?php if(!empty($materials)): ?>
                            <?php $c = 0; foreach ($materials as $v): $c++; ?>
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label" for="firstName">Vật liệu</label>
                                        <?php
                                            $selected[$v->getMaterialId()] = ['label' => $v->getOption('materialName'), 'value' => $v->getMaterialId(), 'selected' => true];
                                        ?>
                                        <input type="hidden" value="<?php echo $v->getId() ?>" name="pmId[]">
                                        <?= $this->formelement($form->get('materialId')->setValueOptions($selected)->setAttributes(['name' => 'materialId[]', 'value'=> $v->getMaterialId(), 'class' => 'form-control select-ajax-material','data-cong' => 'false', 'required' => 'required', 'placeholder'=>'Vật liệu','data-parsley-type' => 'string', 'data-parsley-error-message' => 'Vật liệu không được để trống'])) ?>
                                        <?= $this->formelementerrors($form->get('materialId'),['class' => 'parsley-errors-list filled']) ?>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label" for="firstName">Đơn giá</label>
                                        <?= $this->formelement($form->get('price')->setAttributes(['name' => 'price[]','value'=> $v->getPrice(), 'class' => 'price_field form-control autonumber', 'placeholder'=>'Đơn giá', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                        <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label" for="firstName">Số lượng</label>
                                        <?= $this->formelement($form->get('quantity')->setAttributes(['name' => 'quantity[]', 'value'=> $v->getQuantity(), 'class' => 'quantity_field form-control', 'placeholder'=>'Số lượng', 'required' => 'required', 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                        <?= $this->formelementerrors($form->get('quantity'),['class' => 'parsley-errors-list filled']) ?>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label" for="firstName">Thành tiền</label>
                                        <div class="input-group">
                                            <?= $this->formelement($form->get('intoMoney')->setAttributes(['name' => 'intoMoney[]', 'value'=> $v->getIntoMoney(),'class' => 'intoMoney_field form-control autonumber', 'placeholder'=>'Thành tiền'])) ?>
                                            <?= $this->formelementerrors($form->get('intoMoney'),['class' => 'parsley-errors-list filled']) ?>
                                            <span class="input-group-btn">
                                                <button type="button" id="check-minutes" data-material="<?php echo $v->getMaterialId() ?>" data-product="<?php echo $form->get('productId')->getValue() ?>" class="btn remove-product-item"> - </button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Vật liệu</label>
                                    <?= $this->formelement($form->get('materialId')->setAttributes(['name' => 'materialId[]', 'value' => '1', 'class' => 'form-control select-ajax-material','data-cong' => 'false', 'required' => 'required', 'placeholder'=>'Vật liệu','data-parsley-type' => 'string', 'data-parsley-error-message' => 'Vật liệu không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('materialId'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Đơn giá</label>
                                    <?= $this->formelement($form->get('price')->setAttributes(['name' => 'price[]','class' => 'price_field form-control autonumber', 'placeholder'=>'Đơn giá', 'required' => 'required', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Số lượng</label>
                                    <?= $this->formelement($form->get('quantity')->setAttributes(['name' => 'quantity[]','class' => 'quantity_field form-control', 'placeholder'=>'Số lượng', 'required' => 'required', 'data-parsley-type' => 'string', 'data-parsley-error-message' => 'Không được để trống'])) ?>
                                    <?= $this->formelementerrors($form->get('quantity'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label" for="firstName">Thành tiền</label>
                                    <?= $this->formelement($form->get('intoMoney')->setAttributes(['name' => 'intoMoney[]','class' => 'intoMoney_field form-control autonumber', 'placeholder'=>'Thành tiền'])) ?>
                                    <?= $this->formelementerrors($form->get('intoMoney'),['class' => 'parsley-errors-list filled']) ?>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'loadHomepage btn btn-default', 'value' => 'Cập nhật']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card-box">
                <input type="hidden" name="image" value="<?= $image ?>" />
                <img class="img-fluid img-thumbnail lazy" data-src="<?= $image ?>" />
            </div>
        </div>

        <!-- End col-sm-8 -->
    </div>
</form>
