<?php
    $form = $this->form;
    $materials = $this->materials;
    $type = $form->get('type')->getValue();
    echo $this->headtitle($this->escapehtml($this->translate('Sửa - '.$form->get('name')->getValue())));
?>

<form class="material-form" method="post" enctype="multipart/form-data" data-parsley-validate novalidate>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="portlet-title">
                    <h4 class="m-t-0 header-title m-b-20"><b>Chi tiết vật liệu</b></h4>
                </div>
                <div class="portlet-body form">
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Đơn vị</label>
                                <input type="hidden" name="type" value="<?= $form->get('type')->getValue() ?>" >
                                <?= $this->formelement($form->get('type')->setAttributes(['class' => 'form-control material-type', 'disabled' => true, 'required' => 'required', 'data-parsley-error-message' => 'Đơn vị không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('type'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Tên vật liệu</label>
                                <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control', 'placeholder'=>'Tên vật liệu', 'required' => 'required', 'data-parsley-error-message' => 'Tên vật liệu không được để trống'])) ?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Đơn giá</label>
                                <?php if($type != 3): ?>
                                    <input type="hidden" name="price" value="<?= $form->get('price')->getValue() ?>" >
                                <?php endif; ?>
                                <?= $this->formelement($form->get('price')->setAttributes(['class' => 'form-control autonumber', 'placeholder'=>'Đơn giá','data-parsley-type' => 'string', 'disabled' => ($type == 3 ? false:true)])) ?>
                                <?= $this->formelementerrors($form->get('price'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label" for="firstName">Nhà cung cấp</label>
                                    <input type="hidden" name="manufactureId" value="<?= $form->get('manufactureId')->getValue() ?>" >
                                <?= $this->formelement($form->get('manufactureId')->setAttributes(['class' => 'form-control', 'disabled' => true])) ?>
                                <?= $this->formelementerrors($form->get('manufactureId'),['class' => 'parsley-errors-list filled']) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table style="margin: 0 0 15px !important;" class="mr-0 dg table table-hover table-condensed">
                                  <tr>
                                    <th>Vật liệu</th>
                                    <th>Đơn giá</th>
                                    <th>Số lượng</th>
                                    <th>Thành tiền</th>
                                    <th>Đơn giá</th>
                                    <th>Tồn kho - số lượng</th>
                                    <th>Tồn kho - thành tiền</th>
                                  </tr>

                                  <?php
                                    foreach ($materials as $v):
                                  ?>
                                <tr>
                                    <td><?= $v->getOptions()['materialName']; ?></td>
                                    <td><?= number_format($v->getPrice()); ?></td>
                                    <td><?= $v->getQuantity(); ?></td>
                                    <td><?= number_format($v->getIntoMoney()); ?></td>

                                    <td><?= number_format($v->getInventoryPrice()); ?></td>
                                    <td><?= $v->getInventoryTotalQuantiy(); ?></td>
                                    <td><?= number_format($v->getInventoryTotalPrice()); ?></td>

                                  </tr>
                            <?php endforeach; ?>
                      </table>
                        </div>
                    </div>
                    <div class="row">

                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'loadHomepage btn btn-default']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>
                </div>
            </div>
        </div>

        <!-- End col-sm-8 -->

    </div>
</form>


