<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách vật liệu')));
$domainUrl = $this->home()->getDomain();
$domainUrl ? $_SERVER['HTTP_HOST'] = $domainUrl:$_SERVER['HTTP_HOST'];
$option = $this->option;
?>
<input type="hidden" class="updateHomepage" />
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a href="/admin/material/add" class="btn btn-default waves-effect waves-light">Thêm vật liệu</a>
                            <a class="btn btn-white waves-effect waves-light" data-toggle="modal" data-target="#modal-import"><i class="ion-ios7-upload-outline" style="font-size: 16px;margin: 0 3px 0 0"></i> Thêm File Excel</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">
                                <form action="" method="get" name="ProductSearch" class="form-inline" id="ProductSearch">
                                    <?php
                                    $form = $this->fFilter;
                                    ?>
                                    <div class="form-group">
                                        <?= $this->formelement($form->get('id')->setAttributes(['class' => 'form-control','placeholder'=>'Mã vật liệu', 'value' => isset($this->query['id']) ? $this->query['id']:'']))?>
                                    </div>
                                    <div class="form-group">
                                        <?= $this->formelement($form->get('name')->setAttributes(['class' => 'form-control','placeholder'=>'Tên vật liệu', 'value' => isset($this->query['name']) ? $this->query['name']:'']))?>
                                    </div>
                                    <div class="form-group"><input name="submit" type="submit" class="btn btn-default " value="Tìm Kiếm"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <?php
                    echo $dg = new \Admin\Dg\DgMaterial ( array (
                        'data' => $this->results->getData (),
                        'paging' => $this->results->getPaging (),
                        'rowCount' => $this->results->getRowCount (),
                        'rowInPage' => $this->results->getRowInPage (),
                        'setup' => true,
                        'url' => $this->url,
                    ));

                    $total = ceil($this->results->getRowCount ()/$this->results->getPaging ()[1]);
                    $page = $this->results->getPaging ()[0];
                    $query = $this->uri;
                    $page_prev = (int)($page == 1 ? 1:$page-1);
                    $page_next = (int)($total == $page ? $page:$page + 1);
                    $link = '';
                    if($query) {
                        $page_prev = preg_replace ( '/page=\d*/i','page='.$page_prev, $query );
                        $page_next = preg_replace ( '/page=\d*/i','page='.$page_next, $query );
                        $link = preg_replace ( '/page=\d*/i','', $query );
                    } else {
                        $page_prev = 'page='.$page_prev;
                        $page_next = 'page='.$page_next;
                    }

                    ?>

                    <label class="m-t-5">Trang:
                        <select class="form-control input-sm" id="paginationControl" size="1">
                            <?php for($c = 1; $c <= $total; $c++): ?>
                                <option value="<?php echo 'material?page='. $c .'&'. $link ?>" <?php echo $c == $page ? 'selected':'' ?>><?php echo $c ?></option>
                            <?php endfor; ?>
                        </select> / <?php echo $total; ?>
                    </label>

                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal-import" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="full-width-modalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <ul class="nav nav-tabs navtab-bg nav-justified">

                <li class="active">
                    <a href="#file-excel" data-toggle="tab" aria-expanded="false">
                        <span class="">File Excel</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="import-coin tab-pane active" id="file-excel">
                    <label id="percentComplete">Lưu ý</label>
                    <p class="text-dark m-b-30 font-13">
                        Import theo mẫu sau
                        <a target="_blank" href="https://docs.google.com/spreadsheets/d/1hjwvDtZ-Pz9F9f4waWRovH9v2mR47DzONqoJh9fOK7A/edit#gid=2026471240">Mẫu</a>
                    </p>
                    <label id="percentComplete">File excel</label>
                    <form class="form_import_coin" name="form_import">
                        <div class="form-group">
                            <input class="excel_file_material filestyle" type="file" name="file_import" data-buttonText="Chọn File Excel"  id="fileName">
                        </div>
                        <div class="form-group">
                            <a class="import-coin__button-import btn btn-insert btn-default waves-effect waves-light">Import</a>
                        </div>
                    </form>
                    <p class="text-danger errors"></p>
                    <p class="text-success success"></p>
                </div>
            </div>

            <div class="modal-footer">
                <input type="hidden" data-value="1" id="pageImage">
                <button type="button" class="btn" data-dismiss="modal">Đóng</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<style>
    .pagination {
        display: none;
    }
</style>