<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách sản xuất')));
$product = $this->results;
$query = $this->query;
$query_router = $this->query_router;
$export_all = $query_router['selectall'] == 'true' ? true:false;
$export_id = $query_router['selected_id'] ? $query_router['selected_id']:false;
$export_id = explode(',', $export_id);
$product_material = $this->product_material;
$order_production = $this->order_production;

use Base\XLSX\XLSXWriter;
use Home\Model\DateBase;
$data = json_encode(array('depotId' => 110912, 'page' => 1, 'statuses' => array('Confirmed')));
$curl = curl_init();
$api = \Base\Model\Resource::data_api();
$data = array(
    'version' => $api['version'],
    'appId' => $api['appId'],
    'businessId' => $api['businessId'],
    'accessToken' => $api['accessToken'],
    'data' => $data
);
curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://open.nhanh.vn/api/order/index',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => $data,
));
$response = curl_exec($curl);
curl_close($curl);
$response = json_decode($response, true);
$totalPage = $response['data']['totalPages'];
$order_product = array();

for($c = 1; $c <= $totalPage; $c++) {
    $data = json_encode(array('depotId' => 110912, 'page' => $c, 'statuses' => array('Confirmed')));
    $curl = curl_init();

    $api = \Base\Model\Resource::data_api();

    $data = array(
        'version' => $api['version'],
        'appId' => $api['appId'],
        'businessId' => $api['businessId'],
        'accessToken' => $api['accessToken'],
        'data' => $data
    );


    curl_setopt_array($curl, array(
        CURLOPT_URL => 'https://open.nhanh.vn/api/order/index',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => $data,
    ));

    $response = curl_exec($curl);
    curl_close($curl);
    $response = json_decode($response, true);
    if(!empty($response['data']['orders'])) {
        foreach ($response['data']['orders'] as $v) {
            foreach ($v['products'] as $vv) {
                $order_product[$v['id']][$vv['productCode']] = array($vv['quantity'], $v['createdDateTime']);
            }
        }
    }
}

?>

<style>
    .list_product > div {
        margin: 0 0 10px;
    }
    .list_product > div:last-child, .list_product > div:last-child p {
        margin: 0;
    }
</style>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="portlet-body">
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="btn-toolbar">
                        <div class="btn-group focus-btn-group">
                            <a class="button-export-all btn btn-default waves-effect waves-light" target="_blank" href="/admin/material/productsx?selectall=true">Xuất tất cả excel</a>
                            <a class="button-export-product-sx btn btn-white waves-effect waves-light " ><i class="ion-ios7-upload-outline" style="font-size: 16px;margin: 0 3px 0 0"></i> Xuất excel đã chọn</a>
                        </div>
                        <div class="btn-group dropdown-btn-group pull-right">
                            <div class="dataTables_filter mb-15">

                            </div>
                        </div>
                    </div>
                    <div class="dg-container">
                        <table class="product_list dg table table-bordered table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th style="width: 0.2%;"></th>
                                    <th style="width: 1%;">Hình ảnh</th>
                                    <th style="width: 10%;">Mã sản phẩm</th>
                                    <th style="width: 10%;">Tên sản phẩm</th>
                                    <th style="width: 5%;">Tồn kho</th>
                                    <th style="vertical-align: middle;width: 12%;">Đơn hàng</th>
                                    <th style="text-align: center;vertical-align: middle;width: 5%;">Hoạt động</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(!empty($product)): ?>
                                    <?php
                                    $show = false;
                                    // start product
                                    $stock = 0; $stock_check = false; $approved = false; $approved_is = true; $materials = array();
                                    $product_is_production = false;
                                    $product_is_finished = false;
                                    $start_time = '';
                                    $end_time = '';
                                    $export = array();
                                    foreach($product as $k => $v):
                                        $orderId = '';
                                        $order_desc = '';
                                        $quantity_sx = 0;
                                        $order_string = '';
                                        foreach ($order_product as $kk => $oe) {
                                            if(isset($oe[$k])) {
                                                $show = true;
                                                $orderId .= 'Đơn hàng <strong>'. $kk . '</strong> Số lượng '.$oe[$k][0].' Ngày '.DateBase::toDisplayDateTime($oe[$k][1]).'<br/>';
                                                $order_desc .= 'Đơn hàng '. $kk . ' Số lượng '.$oe[$k][0].' Ngày '.DateBase::toDisplayDateTime($oe[$k][1]).'<br/>';
                                                $quantity_sx += $oe[$k][0];
                                                $order_string .= $kk.'_';
                                                if(isset($order_production[$kk]) && $order_production[$kk]['status'] == \Admin\Model\OrderManufacture::IN_PRODUCTION) {
                                                    if($order_production[$kk][$k]) {
                                                        $product_is_production = true;
                                                    }
                                                }
                                                if(isset($order_production[$kk]) && $order_production[$kk]['status'] == \Admin\Model\OrderManufacture::FINISHED_PRODUCTION) {
                                                    if($order_production[$kk][$k]) {
                                                        $product_is_finished = true;
                                                    }
                                                }
                                                if(in_array($k,$export_id)){
                                                    $export[] = array(
                                                        $v['code'],
                                                        $v['name'],
                                                        $v['image'],
                                                        $v['remain'],
                                                        $kk,
                                                        $oe[$k][0],
                                                    );
                                                }
                                                if($export_all) {
                                                    $export[] = array(
                                                        $v['code'],
                                                        $v['name'],
                                                        $v['image'],
                                                        $v['remain'],
                                                        $kk,
                                                        $oe[$k][0],
                                                    );
                                                }
                                                $start_time = $order_production[$kk]['startDateTime'];
                                                $end_time = $order_production[$kk]['endDateTime'];
                                            }
                                        }
                                    // start show
                                    if($show):
                                    ?>
                                    <?php
                                        $url_created_product = '';
                                        if(isset($product_material[$k])) {
                                            $named = '';
                                            $c = 0;
                                            $products = array();

                                            $approved = true;
                                            if($v['remain'] >= $quantity_sx) {
                                                $approved = false;
                                            } else {
                                                if($v['remain'] > 0) {
                                                    $quantity_sx = $quantity_sx - $v['remain'];
                                                }
                                            }
                                            foreach ($product_material[$k] as $kpi => $pi) {
                                                $c++;
                                                $named .= $c.'. '.$pi['materialName'].' - SL: '.$pi['quantity'] .'<br/>';
                                                $products[] = array(
                                                    'materialId' => $pi['materialId'],
                                                    'quantity' => $pi['quantity'] * $quantity_sx
                                                );
                                            }
                                            if($v['remain'] > $quantity_sx) {
                                                $materials[$order_string.$v['code']] = $products;
                                            }
                                            $url_created_product = '<span class="label label-success" data-toggle="tooltip" data-html="true" data-placement="top" title="" data-original-title="'.$named.'">Vật liệu sử dụng</span>';
                                        } else {
                                            $url_created_product = '<a class="label label-danger" href="'.'/admin/material/addproduct?id='.$k.'&img='.$v['image'].'&name='.$v['name'].'" target="_blank">Tạo vật liệu</a>';
                                        }
//                                        if(in_array($k,$export_id)){
//                                            $export[] = array(
//                                                $v['code'],
//                                                $v['name'],
//                                                $v['image'],
//                                                $order_desc,
//                                                $v['remain'],
//                                            );
//                                        }
//                                        if($export_all) {
//                                            $export[] = array(
//                                                $v['code'],
//                                                $v['name'],
//                                                $v['image'],
//                                                $order_desc,
//                                                $v['remain'],
//                                            );
//                                        }
                                    ?>
                                    <tr class="even">
                                        <td style="width: 0.2%; vertical-align: middle;" class="bs-checkbox "><div class="checkbox"><input type="checkbox" name="productId" value="<?php echo $k ?>"><label></label></div></td>
                                        <td class="id" style="vertical-align: middle"><a title="<?php echo $v['name'] ?>" href="<?php echo $v['image'] ?>" class="button-image"><img class="lazy thumb-md" data-src="<?php echo $v['image'] ?>" ></a></td>
                                        <td style="vertical-align: middle"><strong><?php echo $v['code'] ?></strong> - <?php echo $url_created_product ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['name'] ?></td>
                                        <td style="vertical-align: middle"><?php echo $v['remain'] ?></td>
                                        <td style="vertical-align: middle"><?php echo $orderId ?></td>
                                        <td style="text-align: center;vertical-align: middle">
                                            <?php if($product_is_production): $approved = false; ?>
                                                <span class="label label-warning m-b-5 d-block">Đang sản xuất</span>
                                                <p class="text-muted m-t-5 m-b-5 font-13"><?= 'Ngày bắt đầu: '.DateBase::toDisplayDateTime($start_time) ?></p>
                                                <a data-orders='<?= $order_string ?>' data-code='<?= $v['code'] ?>' class="btn-in-order-finished btn label btn-sm btn-default btn-rounded waves-effect waves-light">Hoàn thành</a>
                                            <?php endif; ?>

                                            <?php if($product_is_finished): $approved = false; ?>
                                                <p class="text-muted m-t-5 m-b-5 font-13"><?= 'Ngày bắt đầu: '.DateBase::toDisplayDateTime($start_time) ?></p>
                                                <span class="label label-success m-b-5 d-block">Hoàn thành</span>
                                                <p class="text-muted m-t-5 m-b-5 font-13"><?= 'Ngày kết thúc: '.DateBase::toDisplayDateTime($end_time) ?></p>
                                            <?php endif; ?>

                                            <?php if($approved): $approved = false; ?>
                                                <a data-orders="<?php echo $order_string ?>" data-code="<?php echo $v['code']; ?>" data-quantity="<?php echo $quantity_sx; ?>" class="btn-in-process btn label btn-sm btn-default btn-rounded waves-effect waves-light">Sản xuất</a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <?php
                                        // end show
                                        endif;
                                        $show = false;
                                        $product_is_production = false;
                                        $product_is_finished = false;
                                        // end product
                                        endforeach;

                                        if(!empty($export)) {
                                            $file_name = 'Danh sách sản phẩm sản xuất_'.date('ymd').'.xlsx';
                                            $sheet_product = 'Product Material';
                                            $header_one = array( 'Mã sản phẩm', 'Tên sản phẩm', 'Hình ảnh sản phẩm', 'Tồn kho', 'Đơn hàng', 'Số lượng');
                                            $styles_white = array('font'=>'Arial', 'font-style'=>'bold', 'fill'=>'#FFF', 'halign'=>'left', 'border'=>'left,right,top,bottom');
                                            $writer = new XLSXWriter();
                                            $writer->writeSheetRow($sheet_product, $header_one, $styles_white);
                                            $printedSeasons = [];
                                            foreach ($export as $pi) {
                                                $sku = $pi[0];
                                                if(!in_array($sku, $printedSeasons)) {
                                                    $printedSeasons[] = $sku;
                                                } else {
                                                    $pi[0] = ' ';
                                                    $pi[1] = ' ';
                                                    $pi[2] = ' ';
                                                    $pi[3] = ' ';
                                                }
                                                $writer->writeSheetRow($sheet_product, $pi);
                                            }
                                            $writer->writeToFile($file_name);
                                            header('Content-Description: File Transfer');
                                            header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                                            header("Content-Disposition: attachment; filename=" . basename($file_name));
                                            header("Content-Transfer-Encoding: binary");
                                            header("Expires: 0");
                                            header("Pragma: public");
                                            header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
                                            header('Content-Length: ' . filesize($file_name));
                                            ob_clean();
                                            flush();
                                            readfile($file_name);
                                            unlink($file_name);
                                            exit;
                                        }
                                        endif;
                                    ?>
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

