<?php
    $data = $this->results;
    $name = $this->UserName;
    echo $this->headtitle($this->escapehtml($this->translate('Bảng điều khiển')));
    $optionPage = $this->home()->optionPage(23);
//    $optionPage = $this->home()->optionPage(15);
    $newsDashboard = $optionPage['bai-viet-dashboard'];
?>
<style>
    .video__item {
        margin: 20px auto 0;
        position: relative;
        padding-bottom: 55.6%;
        height: 0;
    }
    .video__item iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header m-t-0">Xin chào: <?= strtoupper($name) ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="card-box widget-inline">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="widget-inline-box text-center">
                            <h3><i class="text-primary md md-add-shopping-cart"></i> <b data-plugin="counterup">4477</b></h3>
                            <h4 class="text-muted font-16">Lifetime total sales</h4>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="widget-inline-box text-center">
                            <h3><i class="text-custom md md-attach-money"></i> <b data-plugin="counterup">3920</b></h3>
                            <h4 class="text-muted font-16">Income amounts</h4>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="widget-inline-box text-center">
                            <h3><i class="text-pink md md-account-child"></i> <b data-plugin="counterup">3260</b></h3>
                            <h4 class="text-muted font-16">Total users</h4>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="widget-inline-box text-center b-0">
                            <h3><i class="text-purple md md-visibility"></i> <b data-plugin="counterup">162</b></h3>
                            <h4 class="text-muted font-16">Total visits</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
