<?php
    $data = $this->results;
    $name = $this->UserName;
    echo $this->headtitle($this->escapehtml($this->translate('Bảng điều khiển')));
    $optionPage = $this->home()->optionPage(23);
//    $optionPage = $this->home()->optionPage(15);
    $newsDashboard = $optionPage['bai-viet-dashboard'];
?>
<style>
    .video__item {
        margin: 20px auto 0;
        position: relative;
        padding-bottom: 55.6%;
        height: 0;
    }
    .video__item iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
</style>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <h3 class="page-header m-t-0">Xin chào: <?= strtoupper($name) ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">DÀNH CHO NGƯỜI MỚI BẮT ĐẦU</h3>
            </div>
            <div class="panel-body">
                <ul class="p-l-r-10 m-b-30">
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup">Cài đặt logo, favicon, tiêu đề trang</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/page/homepage">Cài đặt tuỳ chỉnh khác Head/ Footer</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup/template">Cài đặt hiển thị trang chủ</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/setup/other">Cài đặt tên miền riêng</a></li>
                    <li class="m-b-10"><a class="text-primary" href="/admin/user">Thêm tài khoản quản lý/ phân quyền hiển thị tính năng</a></li>
                </ul>
                <div class="admin-dashboard__support">
                    <figure class="admin-dashboard__support--icon"></figure>
                    <p>
                        Nếu bạn cần thêm sự hỗ trợ, hãy liên hệ với chúng tôi
                        <br/>
                        Hotline: <b>0986 174 666</b>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
